# Generated by Django 2.1.4 on 2018-12-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('images', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('profile', models.CharField(max_length=200)),
                ('urls', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('thumb', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('images', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('formats', models.CharField(max_length=200)),
                ('styles', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('artist', models.ManyToManyField(to='inasilentway.Artist')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inasilentway.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inasilentway.Record')),
            ],
        ),
    ]
