# Generated by Django 2.1.4 on 2018-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0003_remove_track_discogs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
