# Generated by Django 2.1.4 on 2018-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0005_auto_20181210_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='urls',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
