# Generated by Django 2.1.4 on 2018-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0006_auto_20181210_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
