# Generated by Django 2.1.4 on 2018-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0007_auto_20181210_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='genres',
        ),
        migrations.AddField(
            model_name='record',
            name='genres',
            field=models.ManyToManyField(to='inasilentway.Genre'),
        ),
    ]
