# Generated by Django 2.1.4 on 2018-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0009_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='styles',
        ),
        migrations.AddField(
            model_name='record',
            name='styles',
            field=models.ManyToManyField(to='inasilentway.Style'),
        ),
    ]
