# Generated by Django 2.1.4 on 2018-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0010_auto_20181210_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrobble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
