# Generated by Django 2.1.4 on 2018-12-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0011_scrobble'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrobble',
            name='isw_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inasilentway.Record'),
        ),
        migrations.AddField(
            model_name='scrobble',
            name='isw_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inasilentway.Artist'),
        ),
        migrations.AddField(
            model_name='scrobble',
            name='isw_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inasilentway.Track'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
