# Generated by Django 2.1.4 on 2018-12-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasilentway', '0012_auto_20181210_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
